export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';

export const UPDATE_JOB_DETAILS = 'UPDATE_JOB_DETAILS';
export const UPDATE_JOB = 'UPDATE_JOB';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const UPDATE_MSG = 'UPDATE_MSG';
export const ADD_JOB_DETAILS = 'ADD_JOB_DETAILS';
